export enum ActionTypes {
  FETCH_ALL_DEMO_SUCCESS = "FETCH_ALL_DEMO_SUCCES",
  FETCH_ALL_DEMO_FAILED = "FETCH_ALL_DEMO_FAILED",

  DELETE_ALL_DEMO_SUCCESS = "DELETE_ALL_DEMO_SUCCESS",
  DELETE_ALL_DEMO_FAILED = "DELETE_ALL_DEMO_FAILED",

  FETCH_DEMO_SUCCESS = "FETCH_DEMO_SUCCES",
  FETCH_DEMO_FAILED = "FETCH_DEMO_FAILED",

  DELETE_DEMO_SUCCESS = "DELETE_DEMO_SUCCESS",
  DELETE_DEMO_FAILED = "DELETE_DEMO_FAILED",

  CREATE_DEMO_SUCCESS = "CREATE_DEMO_SUCCESS",
  CREATE_DEMO_FAILED = "CREATE_DEMO_FAILED",

  EdITE_DEMO_SUCCESS = "EdITE_DEMO_SUCCES",
  EdITE_DEMO_FAILED = "EdITE_DEMO_FAILED",
}
